{% set name = "netgen" %}
{% set version = "6.2.2105" %}
{% set branch = "master" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/NGSolve/netgen
  git_branch: {{ branch }}
  patches:
    - solids-volume.patch

build:
  number: 0
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}
    - ninja
    - cmake
  host:
    - occt
    - python
    - pybind11
    - zlib
  run:
    - occt
    - python
    - zlib

test:
  commands:
    - python -c "import sys; print(sys.version); import netgen; from netgen import occ; face = occ.WorkPlane().Rectangle(3, 4).Face()"

about:
  home: https://sourceforge.net/projects/netgen-mesher/
  license: LGPL2.1
  license_family: LGPL
  summary: NETGEN is an automatic 3d tetrahedral mesh generator 
  description: NETGEN is an automatic 3d tetrahedral mesh generator. It accepts input from constructive solid geometry (CSG) or boundary representation (BRep) from STL file format. The connection to a geometry kernel allows the handling of IGES and STEP files. NETGEN contains modules for mesh optimization and hierarchical
    mesh refinement. Netgen is open source based on the LGPL license. It is available for Unix/Linux and Windows.
  doc_url: http://www.hpfem.jku.at/netgen/
  dev_url: https://sourceforge.net/projects/netgen-mesher/

extra:
  recipe-maintainers:
    - L-Nafaryus 
